name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14.7.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Run Tests
        run: |
          npm ci
          npm test
          bash -c '/bin/bash <(curl -s https://codecov.io/bash)'
