branches: 
  - main
repositoryUrl: https://github.com/liatrio/gratibot.git
preset: conventionalcommits
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
