name: "prod"
on:
  push:
    tags:
      - v*.*.0

  workflow_dispatch:
    inputs:
      gratibot_limit:
        description: "The amount of fistbumps that a user can give for one day."
        required: false
        default: "5"
        type: string

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/gratibot

jobs:
  build:
    name: Tag image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || contains(fromJSON('["Pactionly", "gesparza3"]'), github.actor)
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
          labels: runnumber=${{ github.run_id }}

    outputs:
      docker_tag: ${{ steps.tag.outputs.tag }}
  plan:
    name: "Terraform Prod plan"
    runs-on: ubuntu-latest
    environment:
      name: "prod-plan"
    container: "hashicorp/terraform:0.14.10"
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Plan Gratibot prod deployment
        working-directory: tf
        run: |
          terraform init -backend-config=backends/prod.tf
          terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: "1b4a4fed-fed8-4823-a8a0-3d5cea83d122"
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
          TF_VAR_acr_subscription_id: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
          TF_VAR_instance_capacity: "2"
          TF_VAR_gratibot_image: "${{ env.IMAGE_NAME }}:${{ needs.build.outputs.docker_tag }}"
          TF_VAR_environment: "prod"
          TF_VAR_app_token: ${{ secrets.PROD_PLAN_APP_TOKEN }}
          TF_VAR_bot_user_token: ${{ secrets.PROD_PLAN_BOT_TOKEN }}
          TF_VAR_gratibot_recognize_emoji: ":fistbump:"
          TF_VAR_gratibot_limit: ${{ inputs.gratibot_limit }}
  apply:
    name: "Terraform Prod Apply"
    runs-on: ubuntu-latest
    environment:
      name: "prod"
    container: "hashicorp/terraform:0.14.10"
    needs: [build, plan]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Gratibot to Prod
        working-directory: tf
        run: |
          terraform init -backend-config=backends/prod.tf
          terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: "1b4a4fed-fed8-4823-a8a0-3d5cea83d122"
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
          TF_VAR_acr_subscription_id: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
          TF_VAR_instance_capacity: "2"
          TF_VAR_gratibot_image: "${{ env.IMAGE_NAME }}:${{ needs.build.outputs.docker_tag }}"
          TF_VAR_environment: "prod"
          TF_VAR_app_token: ${{ secrets.PROD_APP_TOKEN }}
          TF_VAR_bot_user_token: ${{ secrets.PROD_BOT_TOKEN }}
          TF_VAR_gratibot_recognize_emoji: ":fistbump:"
          GRATIBOT_LIMIT: ${{ inputs.gratibot_limit }}
