
name: "Publish"
on:
  push:
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/gratibot
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    container: gcr.io/k8s-skaffold/skaffold:v1.3.1
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:${IMAGE_TAG:0:7} --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push $IMAGE_ID:${IMAGE_TAG:0:7}
